################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_datatypes_format.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_datatypes_internal.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_layer_custom_interface.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_log.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_math_elementwise_mul_int8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_math_elementwise_sum_int8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_math_helpers.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_platform.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_platform_interface.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/ai_platform_interface_stai.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_avgpool_get_buffer_sizes_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_avgpool_get_buffer_sizes_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_avgpool_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_avgpool_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_batch_matmul_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_batch_matmul_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_concatenation_s8_w.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_concatenation_s8_x.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_concatenation_s8_y.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_concatenation_s8_z.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_1_x_n_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_1_x_n_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_1x1_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_1x1_s4_fast.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_1x1_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_1x1_s8_fast.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_even_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_get_buffer_sizes_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_get_buffer_sizes_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_get_buffer_sizes_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_wrapper_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_wrapper_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_convolve_wrapper_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_3x3_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_fast_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_get_buffer_sizes_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_get_buffer_sizes_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_get_buffer_sizes_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_s4_opt.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_s8_opt.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_wrapper_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_wrapper_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_depthwise_conv_wrapper_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_elementwise_add_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_elementwise_add_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_elementwise_mul_acc_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_elementwise_mul_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_elementwise_mul_s16_batch_offset.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_elementwise_mul_s16_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_elementwise_mul_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_fully_connected_get_buffer_sizes_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_fully_connected_get_buffer_sizes_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_fully_connected_per_channel_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_fully_connected_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_fully_connected_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_fully_connected_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_fully_connected_wrapper_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_lstm_unidirectional_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_lstm_unidirectional_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_max_pool_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_max_pool_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_maximum_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_minimum_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_activation_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_depthwise_conv_nt_t_padded_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_depthwise_conv_nt_t_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_depthwise_conv_nt_t_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_depthwise_conv_nt_t_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_depthwise_conv_s8_core.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_lstm_calculate_gate_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_lstm_calculate_gate_s8_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_lstm_step_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_lstm_step_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mul_core_1x_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mul_core_1x_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mul_core_4x_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_kernel_row_offset_s8_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_kernel_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_kernel_s4_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_kernel_s8_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_nt_interleaved_t_even_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_nt_t_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_nt_t_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_nt_t_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_nt_t_s8_s32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_mat_mult_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_softmax_common_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_transpose_conv_row_s8_s32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_vec_mat_mul_result_acc_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_vec_mat_mul_result_acc_s8_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_vec_mat_mult_t_per_ch_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_vec_mat_mult_t_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_vec_mat_mult_t_s16_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_vec_mat_mult_t_s4.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_vec_mat_mult_t_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nn_vec_mat_mult_t_svdf_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_nntables.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_pad_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_q7_to_q15_with_offset.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_relu6_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_relu_q15.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_relu_q7.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_reshape_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_s8_to_s16_unordered_with_offset.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_softmax_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_softmax_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_softmax_s8_s16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_softmax_u8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_svdf_get_buffer_sizes_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_svdf_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_svdf_state_s16_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_transpose_conv_get_buffer_sizes_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_transpose_conv_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_transpose_conv_wrapper_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_transpose_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_vector_sum_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/arm_vector_sum_s8_s64.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/core_common.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/core_convert.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/core_mem_manager.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/core_net_inspect.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/core_ring_buffer.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/core_utils.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_argminmax.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_avepool_is8os8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_bn_internal.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_bn_is16os1ws16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_bn_is8os8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_bn_is8os8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_bn_iu8ou8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_bn_iu8ou8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_dorefa_is8os1ws8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_if32of32wf32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_is16os16ws1_fxp.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_is16os1ws1_bn_fxp.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_is1os16ws1_bn_fxp.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_is1os1ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_is1os8ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_is1ou16ws1_bn_fxp.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_is8os1ws8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_conv2d_sssa8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_convert.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_dense_is8os1ws1_bn_fxp.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_dense_is8os8ws8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_dense_is8os8ws8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_dw_ch1st_sssa8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_dw_is1os1ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_dw_sssa8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_lstm_is8os8ws8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_maxpool_is16os16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_maxpool_is1os1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_maxpool_is8os8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_maxpool_is8os8_scalepos.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_maxpool_iu16ou16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_maxpool_iu8ou8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_pad_generic.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_pad_is1os1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_pool_f32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_pw_is1of32ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_pw_is1os1ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_pw_is1os8ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_pw_sssa8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_resize.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_upsample.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/forward_lite_upsample_generic.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_argminmax_stm32_integer.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_concat_is1os1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_dorefa_is8os1ws8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_generic_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_integer_scratch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_is16os16ws1_fxp.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_is16os1ws1_bn_fxp.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_is1os16ws1_bn_fxp.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_is1os1ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_is1os8ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_is1ou16ws1_bn_fxp.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_is8os1ws8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_is8os8ws1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_rgb_sssa8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_sssa8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_conv2d_stm32_integer.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_dense_dqnn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_dw_ch1st_sssa8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_dw_is1os1ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_dw_sssa8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_formats_converters.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_generic_fixed.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_generic_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_lstm_is8os8ws8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_maxpool_is1os1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_ml_generic_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_ml_iforest.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_ml_linearclassifier_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_ml_svc_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_ml_svmregressor_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_ml_treeensembleclassifier_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_ml_treeensembleregressor_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_nl_generic_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_nl_stm32_integer.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_norm_generic_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_norm_stm32_integer.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_pad_generic.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_pad_is1os1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_pool_generic_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_pool_stm32_integer.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_pw_is1of32ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_pw_is1os1ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_pw_is1os8ws1_bn.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_pw_sssa8_ch.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_resize.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_rnn_generic_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_stm32_integer.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_template.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_upsample.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/layers_upsample_generic.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_argminmax_if32_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_argminmax_is8_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_bilinear_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_bn_f32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_convert_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_core_errors.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_dense_if32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_dense_is1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_dense_is1ws1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_dense_ws1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_generic_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_gru_f32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_nl_generic_float.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_nl_generic_integer.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_nl_relu_if32of32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_nl_softmax_if32of32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_nl_softmax_is8os8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_nl_softmax_iu8ou8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_norm_if32of32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_norm_if32of32_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/lite_upsample_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_align_factor.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_common_tables.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_dot_prod_f32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_f32_to_int16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_f32_to_int8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_i8o1w8_mat_mult_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_i8o1w8_mat_mult_kernel_dorefa.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_i8o8w1_mac_functions.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_i8o8w1_network_functions.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int16_fill.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int16_shift.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int16_to_f32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int16_to_int8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int8_fill.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int8_pool.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int8_reordered_no_shift.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int8_shift.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int8_to16_no_shift.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int8_to_f32.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_int8_to_int16.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_padding_opt.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_convolve.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_convolve_1x1_s8_fast.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_convolve_dw_3x3_ch1st.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_convolve_dw_ch1st_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_convolve_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_dense.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_nn_mat_mult_conv2d_nt_t.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_nn_mat_mult_deep_conv2d_3x3.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_nn_mat_mult_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_nn_mat_mult_kernel_opt.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_nn_mat_mult_kernel_single_opt.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_nn_mat_mult_nt_t.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_nn_mat_mult_nt_t_s8.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_ch_nn_mat_mult_pw_nt_t.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_convolve.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_convolve_1x1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_convolve_dw.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_convolve_rgb.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_dense.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_dense_loop.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_nn_mat_mult_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_nn_mat_mult_kernel_opt.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_sssa8_nn_mat_mult_nt_t.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_ch_convolve.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_ch_convolve_1x1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_ch_convolve_dw.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_ch_convolve_rgb.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_ch_dense.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_ch_nn_mat_mult_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_ch_nn_mat_mult_nt_t.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_convolve.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_convolve_1x1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_convolve_dw.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_convolve_rgb.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_dense.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_nn_mat_mult_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_ssua8_nn_mat_mult_nt_t.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_ch_convolve.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_ch_convolve_1x1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_ch_convolve_dw.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_ch_convolve_rgb.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_ch_dense.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_ch_nn_mat_mult_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_ch_nn_mat_mult_nt_t.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_convolve.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_convolve_1x1.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_convolve_dw.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_convolve_rgb.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_dense.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_nn_mat_mult_kernel.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uaua8_nn_mat_mult_nt_t.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uint8_fill.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uint8_pool.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uint8_reordered_no_shift.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/st_uint8_to16_no_shift.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/stai_debug.o \
../Middlewares/ST/AI/Lib/NetworkRuntime1020_CM55_GCC/stai_internal.o 


# Each subdirectory must supply rules for building sources it contributes

