################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/iseg_pp_yolov8.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/mpe_pp_yolov8.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_centernet.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_ssd.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_ssd_st.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_st_yolox.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_yolov2.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_yolov5.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_yolov8.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/pd_pp_model.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/spe_movenet_pp.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/sseg_pp_deeplabv3.c \
C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/vision_models_pp.c 

OBJS += \
./Middlewares/STM32_VISION_MODELS_PP/iseg_pp_yolov8.o \
./Middlewares/STM32_VISION_MODELS_PP/mpe_pp_yolov8.o \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_centernet.o \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd.o \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd_st.o \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_st_yolox.o \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov2.o \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov5.o \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov8.o \
./Middlewares/STM32_VISION_MODELS_PP/pd_pp_model.o \
./Middlewares/STM32_VISION_MODELS_PP/spe_movenet_pp.o \
./Middlewares/STM32_VISION_MODELS_PP/sseg_pp_deeplabv3.o \
./Middlewares/STM32_VISION_MODELS_PP/vision_models_pp.o 

C_DEPS += \
./Middlewares/STM32_VISION_MODELS_PP/iseg_pp_yolov8.d \
./Middlewares/STM32_VISION_MODELS_PP/mpe_pp_yolov8.d \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_centernet.d \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd.d \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd_st.d \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_st_yolox.d \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov2.d \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov5.d \
./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov8.d \
./Middlewares/STM32_VISION_MODELS_PP/pd_pp_model.d \
./Middlewares/STM32_VISION_MODELS_PP/spe_movenet_pp.d \
./Middlewares/STM32_VISION_MODELS_PP/sseg_pp_deeplabv3.d \
./Middlewares/STM32_VISION_MODELS_PP/vision_models_pp.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_VISION_MODELS_PP/iseg_pp_yolov8.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/iseg_pp_yolov8.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/mpe_pp_yolov8.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/mpe_pp_yolov8.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/od_pp_centernet.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_centernet.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_ssd.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd_st.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_ssd_st.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/od_pp_st_yolox.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_st_yolox.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov2.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_yolov2.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov5.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_yolov5.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov8.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/od_pp_yolov8.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/pd_pp_model.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/pd_pp_model.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/spe_movenet_pp.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/spe_movenet_pp.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/sseg_pp_deeplabv3.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/sseg_pp_deeplabv3.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_VISION_MODELS_PP/vision_models_pp.o: C:/Users/Middlewares/STM32_VISION_MODELS_PP/Src/vision_models_pp.c Middlewares/STM32_VISION_MODELS_PP/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"C:/Users/Drivers/BSP/NORFlash" -I"C:/Users/Drivers/BSP/HyperRAM" -I"C:/Users/Drivers/BSP/LED" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/LCD" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Drivers/BSP/BUS" -I"C:/Users/Drivers/BSP/UART" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"C:/Users/Middlewares/STM32_MW_ISP/isp/Inc" -I"C:/Users/Middlewares/STM32_MW_ISP/evision/Inc" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_ISP" -I"C:/Users/Middlewares/STM32_MW_CAMERA" -I"C:/Users/Middlewares/STM32_MW_CAMERA/sensors" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Appli/STM32_MW_CAMERA" -I"C:/Users/Middlewares/AI/Inc" -I"C:/Users/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"C:/Users/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"C:/Users/dahuange/Desktop/992_AI_Image_Classification/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-STM32_VISION_MODELS_PP

clean-Middlewares-2f-STM32_VISION_MODELS_PP:
	-$(RM) ./Middlewares/STM32_VISION_MODELS_PP/iseg_pp_yolov8.cyclo ./Middlewares/STM32_VISION_MODELS_PP/iseg_pp_yolov8.d ./Middlewares/STM32_VISION_MODELS_PP/iseg_pp_yolov8.o ./Middlewares/STM32_VISION_MODELS_PP/iseg_pp_yolov8.su ./Middlewares/STM32_VISION_MODELS_PP/mpe_pp_yolov8.cyclo ./Middlewares/STM32_VISION_MODELS_PP/mpe_pp_yolov8.d ./Middlewares/STM32_VISION_MODELS_PP/mpe_pp_yolov8.o ./Middlewares/STM32_VISION_MODELS_PP/mpe_pp_yolov8.su ./Middlewares/STM32_VISION_MODELS_PP/od_pp_centernet.cyclo ./Middlewares/STM32_VISION_MODELS_PP/od_pp_centernet.d ./Middlewares/STM32_VISION_MODELS_PP/od_pp_centernet.o ./Middlewares/STM32_VISION_MODELS_PP/od_pp_centernet.su ./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd.cyclo ./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd.d ./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd.o ./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd.su ./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd_st.cyclo ./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd_st.d ./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd_st.o ./Middlewares/STM32_VISION_MODELS_PP/od_pp_ssd_st.su ./Middlewares/STM32_VISION_MODELS_PP/od_pp_st_yolox.cyclo ./Middlewares/STM32_VISION_MODELS_PP/od_pp_st_yolox.d ./Middlewares/STM32_VISION_MODELS_PP/od_pp_st_yolox.o ./Middlewares/STM32_VISION_MODELS_PP/od_pp_st_yolox.su ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov2.cyclo ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov2.d ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov2.o ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov2.su ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov5.cyclo ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov5.d ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov5.o ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov5.su ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov8.cyclo ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov8.d ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov8.o ./Middlewares/STM32_VISION_MODELS_PP/od_pp_yolov8.su ./Middlewares/STM32_VISION_MODELS_PP/pd_pp_model.cyclo ./Middlewares/STM32_VISION_MODELS_PP/pd_pp_model.d ./Middlewares/STM32_VISION_MODELS_PP/pd_pp_model.o ./Middlewares/STM32_VISION_MODELS_PP/pd_pp_model.su ./Middlewares/STM32_VISION_MODELS_PP/spe_movenet_pp.cyclo ./Middlewares/STM32_VISION_MODELS_PP/spe_movenet_pp.d ./Middlewares/STM32_VISION_MODELS_PP/spe_movenet_pp.o ./Middlewares/STM32_VISION_MODELS_PP/spe_movenet_pp.su ./Middlewares/STM32_VISION_MODELS_PP/sseg_pp_deeplabv3.cyclo ./Middlewares/STM32_VISION_MODELS_PP/sseg_pp_deeplabv3.d ./Middlewares/STM32_VISION_MODELS_PP/sseg_pp_deeplabv3.o ./Middlewares/STM32_VISION_MODELS_PP/sseg_pp_deeplabv3.su ./Middlewares/STM32_VISION_MODELS_PP/vision_models_pp.cyclo ./Middlewares/STM32_VISION_MODELS_PP/vision_models_pp.d ./Middlewares/STM32_VISION_MODELS_PP/vision_models_pp.o ./Middlewares/STM32_VISION_MODELS_PP/vision_models_pp.su

.PHONY: clean-Middlewares-2f-STM32_VISION_MODELS_PP

